#!/usr/bin/env python3
"""
Generate LaTeX macros from CSV data files.

This script reads CSV files from data/ and generates generated/numbers.tex
containing LaTeX macros for all numerical values used in the paper.

Usage:
    python scripts/generate_numbers.py

Workflow to add new numbers:
    1. Add/update CSV file in data/ directory
    2. Add a processing function below (e.g., process_my_data())
    3. Register it in PROCESSORS dict at the bottom
    4. Run: make numbers (or python scripts/generate_numbers.py)
    5. Use the macro in your paper: \\MyNewMacro{}

Naming convention:
    - Macros are CamelCase with no underscores
    - Prefix with category: e.g., EvalIraLSpeedup, TableTwoColA
    - Numbers are formatted appropriately (commas for large ints, precision for floats)
"""

import csv
import os
import sys
from pathlib import Path
from typing import Any

# Import processors
from process_bytes_per_cache_entry import process_bytes_per_cache_entry
from process_io_trace import process_io_trace
from process_op_distribution import process_op_distribution
from process_intra_block_frequency import process_intra_block_frequency
from process_access_concentration import process_access_concentration
from process_ephemeral_keys import process_ephemeral_keys
from process_evaluation import process_evaluation
from process_source_annotations import process_source_annotations

# Paths
# Bundled artifact layout: data lives at <REPO_ROOT>/data, this script and
# outputs at <REPO_ROOT>/artifact/{scripts,generated,figures}/.
import os
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent          # artifact/
REPO_ROOT = PROJECT_ROOT.parent            # repo root
DATA_DIR = Path(os.environ.get("ARTIFACT_DATA", str(REPO_ROOT / "data")))
OUTPUT_FILE = Path(os.environ.get("ARTIFACT_NUMBERS_TEX", str(PROJECT_ROOT / "generated" / "numbers.tex")))


def format_int(n: int) -> str:
    """Format integer with commas: 1234567 -> 1,234,567"""
    return f"{n:,}"


def format_float(n: float, precision: int = 2) -> str:
    """Format float with given precision: 3.14159 -> 3.14"""
    return f"{n:.{precision}f}"


def format_percent(n: float, precision: int = 2) -> str:
    """Format as percentage (assumes n is already in percent): 90.123 -> 90.12"""
    return f"{n:.{precision}f}"


def format_speedup(n: float, precision: int = 2) -> str:
    """Format speedup value: 3.21 -> 3.21"""
    return f"{n:.{precision}f}"


def sanitize_macro_name(name: str) -> str:
    """Convert a string to a valid LaTeX macro name (CamelCase, no special chars)."""
    # Remove special characters, convert to CamelCase
    words = name.replace("_", " ").replace("-", " ").split()
    return "".join(word.capitalize() for word in words)


class MacroCollection:
    """Collects macros and writes them to a .tex file."""

    def __init__(self):
        self.macros: dict[str, str] = {}
        self.sections: list[tuple[str, list[str]]] = []  # (section_name, [macro_names])
        self._current_section: str = "General"
        self._current_section_macros: list[str] = []

    def section(self, name: str):
        """Start a new section in the output file."""
        if self._current_section_macros:
            self.sections.append((self._current_section, self._current_section_macros))
        self._current_section = name
        self._current_section_macros = []

    def add(self, name: str, value: str, comment: str = ""):
        """Add a macro. Name should be CamelCase."""
        if name in self.macros:
            print(f"Warning: Overwriting macro {name}", file=sys.stderr)
        self.macros[name] = (value, comment)
        self._current_section_macros.append(name)

    def write(self, path: Path):
        """Write all macros to a .tex file."""
        # Finalize current section
        if self._current_section_macros:
            self.sections.append((self._current_section, self._current_section_macros))

        lines = [
            "% Auto-generated by scripts/generate_numbers.py",
            "% DO NOT EDIT MANUALLY - changes will be overwritten",
            "%",
            "% Generated from CSV files in data/",
            "% Re-generate with: make numbers",
            "",
        ]

        if not self.macros:
            lines.append("% No data files found in data/")
        else:
            for section_name, macro_names in self.sections:
                lines.append(f"% === {section_name} ===")
                for name in macro_names:
                    value, comment = self.macros[name]
                    if comment:
                        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}  % {comment}")
                    else:
                        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
                lines.append("")

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines))
        print(f"Wrote {len(self.macros)} macros to {path}")


# =============================================================================
# CSV Processors
#
# Add a new function here for each CSV file or data source.
# Each function receives the MacroCollection and adds macros to it.
#
# Example processor:
#
#   def process_my_data(macros: MacroCollection):
#       csv_path = DATA_DIR / "my_data.csv"
#       if not csv_path.exists():
#           return
#
#       macros.section("My Data")
#       with open(csv_path) as f:
#           reader = csv.DictReader(f)
#           for row in reader:
#               macros.add("MyMacroName", format_float(float(row["value"])))
#
# =============================================================================


# =============================================================================
# Main
# =============================================================================

# Register all processors here
PROCESSORS: list = [
    process_bytes_per_cache_entry,
    process_io_trace,
    process_op_distribution,
    process_intra_block_frequency,
    process_access_concentration,
    process_ephemeral_keys,
    process_evaluation,
    process_source_annotations,
]


def main():
    if not DATA_DIR.exists():
        print(f"Creating data directory: {DATA_DIR}")
        DATA_DIR.mkdir(parents=True)

    macros = MacroCollection()

    for processor in PROCESSORS:
        try:
            processor(macros)
        except Exception as e:
            print(f"Error in {processor.__name__}: {e}", file=sys.stderr)
            raise

    # Always write file (even if empty) so LaTeX doesn't fail on \input
    macros.write(OUTPUT_FILE)


if __name__ == "__main__":
    main()
